fix: merge session mode pool config with main config, preserving options
commanded/eventstore pull request #293
Opened 2024-10-26 01:24 UTC by gf3

When providing a session mode pool config via `session_mode_url`, it's not clear that `session_mode_url` is parsed into a keyword list and replaces the parent config.

For example, we use the following configuration to connect to Digital Ocean's managed Postgres:

```elixir
config :our_app, OurApp.EventStore,
  default_database: "defaultdb",
  serializer: Commanded.Serialization.JsonSerializer,
  url: event_store_database_url,
  session_mode_url: event_store_session_database_url,
  ssl: true,
  ssl_opts: [cacertfile: ~c"/etc/ssl/certs/db.ca-certificate.crt", verify: :verify_peer],
  prepare: :unnamed,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  socket_options: maybe_ipv6
```

The options `ssl`, `ssl_opts`, and `prepare` are particularly important to our connection and are not included when generating the config (session mode pool config) from the `session_mode_url`.

This PR merges the session mode pool config _into_ the parent config before passing it along. So that all the specified configuration options are used for the session mode pool, too. Which, I think, is what people probably expect when looking at the above event store configuration.

2024-11-26 19:49 UTC, drteeth requested changes
Hi @gf3, thanks so much for your contribution.

I can see that you are fixing a real world issue, and I'm sure it's correct, but I'm having trouble seeing that from the description of the issue and the code changes.

Can I ask you to include a test that fails without your change and passes with it? This way we won't break it again and the reason for the new implementation will be clear.

Let me know if you need any help with that.

2024-11-27 19:24 UTC, drteeth approved these changes

2024-12-02 15:13 UTC, drteeth commented
@gf3 could you rebase against master again so that these tests will pass?

2024-12-02 19:48 UTC, gf3 commented
@drteeth rebased & pushed

2024-12-02 19:54 UTC, gf3 commented
and tests are passing locally: 
![image](https://github.com/user-attachments/assets/95785d5d-2cb6-45fe-ab32-0b9726d994d5)

2024-12-18 16:59 UTC, merged